# Generated by Django 4.2.7 on 2023-11-28 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courseaccess",
            options={
                "verbose_name": "User Course Access",
                "verbose_name_plural": "User Course Access",
            },
        ),
        migrations.AlterModelOptions(
            name="lessonview",
            options={
                "verbose_name": "User Lesson View",
                "verbose_name_plural": "User Lesson Views",
            },
        ),
        migrations.AddField(
            model_name="lessonview",
            name="watch_time",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ManyToManyField(related_name="lessons", to="main.course"),
        ),
        migrations.AlterField(
            model_name="lessonview",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progress",
                to="main.lesson",
            ),
        ),
    ]
